### PR TITLE
Targetting .NET 4.0 instead of 4.5 (because it still works)

### PR DESCRIPTION
**Pull request by picrap**
As the title says... I'm stuck with 4.0 for a few months and would like to work with nein-math anyway.

### CODE REVIEW

**Comment by axelheer** [comment]
You may add

```
<FrameworkPathOverride Condition=" '$(TargetFramework)' == 'net40' ">/usr/lib/mono/4.0-api</FrameworkPathOverride>
```

to `NeinMath.props` in order to make it build under linux.

**Comment by picrap** [comment]
Done (I'm a total noob with such project types and props).

**Comment by axelheer** [comment]
Cross-building should be easier, though. Please don't ask how long I struggled to make it build for two frameworks under two OS... 🤦‍♂️

**Comment by axelheer** [comment]
Thanks! Will publish new version today.

**Pull request merged**
